name: Publish NPM Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v4

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: 'https://registry.npmjs.org'

      - name: ðŸ›  Run version update script
        if: startsWith(github.ref, 'refs/tags/')
        id: version_script
        run: |
          node scripts/new-version.mjs ${{ github.ref_name }}
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: ðŸ”§ Configure Git
        if: startsWith(github.ref, 'refs/tags/') && steps.version_script.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: ðŸ“¤ Commit version changes
        if: startsWith(github.ref, 'refs/tags/') && steps.version_script.outputs.changed == 'true'
        run: |
          git fetch origin ${{ github.event.repository.default_branch }}
          git checkout ${{ github.event.repository.default_branch }}
          git pull
          git add package.json package-lock.json
          git commit -m "chore: update version to ${{ github.ref_name }}"
          git push origin ${{ github.event.repository.default_branch }}

      - name: ðŸ“Œ Update tag to the latest commit
        if: startsWith(github.ref, 'refs/tags/') && steps.version_script.outputs.changed == 'true'
        run: |
          git tag -f ${{ github.ref_name }}
          git push origin -f ${{ github.ref_name }}

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ‘· Build Typescript app
        run: |
          npm run build

      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: ðŸš€ Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}